---
# Test for a .my.cnf file and either load or generate a password
- name: MySQL | Check for existing config
  file: path=/root/.my.cnf state=file
  register: my_cnf_exists
  ignore_errors: True

- name: MySQL | Generate root password
  shell: openssl passwd -in /dev/urandom | head -1
  register: generated_mysql_root_password
  when: my_cnf_exists|failed

- name: MySQL | Lookup root password
  shell: grep 'password=' /root/.my.cnf | sed s/password=//
  register: saved_mysql_root_password
  when: my_cnf_exists|success
  changed_when: False

- name: MySQL | Set root password fact
  set_fact:
    mysql_root_password: "{{ saved_mysql_root_password.stdout|default(generated_mysql_root_password.stdout) }}"
