---
# Database setup for Roundcube.
# pretty much has to run on the db server as this needs SUPER DB
# access, which I'm loath to allow to remote hosts.
#
# To use a different storage engine this part would have to be
# rewritten.

- name: MySQL | Create database for Roundcube
  mysql_db:
    name: "{{ app_db_name }}"
    state: present
  register: new_database_created

- name: MySQL | Create MySQL user for application
  mysql_user:
    name: "{{ app_db_user }}"
    password: "{{ app_db_password }}"
    priv: "{{ app_db_name }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER,CREATE TEMPORARY TABLES"
    host: "{{ hostvars[item]['ec2_private_dns_name'] }}"
  with_items: groups['tag_type_webserver']

- name: MySQL | Upload database to import for initial bootstrap
  copy:
    src: mysql.initial.sql
    dest: /tmp/
  when: new_database_created|changed

- name: MySQL | Import database for Roundcube
  mysql_db:
    name: "{{ app_db_name }}"
    state: import
    target: /tmp/mysql.initial.sql
  when: new_database_created|changed
