---
# Load balancer.  I've had this time out a few times when testing creation
# not sure why.  Testing directly with boto worked fine.

- name: EC2 | Create HTTP load balancer
  local_action:
    module: ec2_elb_lb
    name: "{{ elb_name }}"
    state: present
    region: "{{ region }}"
    zones: "{{ elb_zones }}"
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
    health_check:
      ping_protocol: http
      ping_port: 80
      ping_path: "/"
      response_timeout: 5
      interval: 10
      unhealthy_threshold: 3
      healthy_threshold: 5
