---
# Launch instances and add them to groups so we can work on them right
# away - in theory.

- name: EC2 | Launch instance
  local_action:
    module: ec2
    key_name: "{{ key_name }}"
    group: "{{ group }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    region: "{{ region }}"
    instance_tags:
      type: "{{ group_name }}"
    wait: true
    exact_count: "{{ exact_count }}"
    count_tag:
      type: "{{ group_name }}"
  register: launched

# This didn't work as I'd hoped.  I'd originally hoped
# to use this to allow starting from an empty host list
# and seamlessly chaining through all created hosts.
# This works, sort of, but there's data in hostvars that
# is populated by the inventory script that doesn't end
# up getting populated this way.  Another one I'd have
# to discuss with someone to see how they do it in real
# life.

- name: EC2 | Add new instance to group
  local_action:
    module: add_host
    name: "{{ item.public_dns_name }}"
    groups: tag_type_{{ group_name }}
  with_items: launched.instances
  when: launched.instances

- name: EC2 | Wait for new instances to listen on port 22
  wait_for:
    state: started
    host: "{{ item.public_dns_name }}"
    port: 22
  with_items: launched.instances
  when: launched.instances
